package school.softgroup.gavryliak_mint;

/**
 * Created by GMisha on 02.02.2017.
 */
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
@DatabaseTable(tableName = "fruits_table")
public class Fruits_Table {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField
    String name;

    Fruits_Table() {
        // needed by ormlite
    }

    public Fruits_Table (String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(id);
        sb.append(". ").append("Fruit name is ").append(name);
        return sb.toString();
    }
}